######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 27 11:38:20 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Image_Buffer.h Image_Viewer.h
SOURCES += Image_Buffer.cpp Image_Viewer.cpp main.cpp
